name       : perl-specio-exporter
version    : '0.42'
release    : 3
source     :
    - https://www.cpan.org/authors/id/D/DR/DROLSKY/Specio-0.42.tar.gz : 23298b93a26d7ae3c1d58106f5898d84ddc71b626afdbf801bddb04d5e524ef6
license    : Artistic-2.0
component  : programming.perl
summary    : Base class for type libraries
description: |
    Base class for type libraries
builddeps  :
    - perl-devel-stacktrace
    - perl-eval-closure
    - perl-module-runtime
    - perl-mro-compat
    - perl-role-tiny
    - perl-sub-quote
    - perl-test-fatal
    - perl-test-needs
    - perl-try-tiny
rundeps    :
    - perl-devel-stacktrace
    - perl-eval-closure
    - perl-module-runtime
    - perl-mro-compat
    - perl-role-tiny
    - perl-sub-quote
    - perl-test-fatal
    - perl-try-tiny
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
