name       : perl-specio-exporter
version    : 0.36
release    : 1
source     :
    - http://search.cpan.org/CPAN/authors/id/D/DR/DROLSKY/Specio-0.36.tar.gz : 1399113b178dd9a2443f0e05bfd5bc665931442bf9e31b223893c7d2853c4480
license    : Artistic-2.0
component  : programming.perl
summary    : Base class for type libraries
description: |
    Base class for type libraries
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
