name       : perl-specio-exporter
version    : '0.42'
release    : 2
source     :
    - https://www.cpan.org/authors/id/D/DR/DROLSKY/Specio-0.42.tar.gz : 23298b93a26d7ae3c1d58106f5898d84ddc71b626afdbf801bddb04d5e524ef6
license    : Artistic-2.0
component  : programming.perl
summary    : Base class for type libraries
description: |
    Base class for type libraries
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
